services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Migrify\ConfigTransformer\FeatureShifter\:
        resource: '../src'
        exclude:
            - '../src/Utils/*'

    Symfony\Component\Filesystem\Filesystem: null