services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Migrify\ConfigTransformer\FormatSwitcher\:
        resource: '../src'
        exclude:
            - '../src/DependencyInjection/Loader/*'

    PhpParser\BuilderFactory: null
    Migrify\ConfigTransformer\FormatSwitcher\PhpParser\Printer\FluentMethodCallPrinter: null

    Symfony\Component\Yaml\Parser: null

    Symplify\SmartFileSystem\FileSystemFilter: null